# Generated by Django 5.0.2 on 2024-03-08 18:20

import booking.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(validators=[booking.models.Booking.validate_date]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.SmallIntegerField(default=1, validators=[booking.models.Booking.validate_guests]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='occasion',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Birthday', 'Birthday'), ('Anniversary', 'Anniversary')], default='Casual', max_length=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(validators=[booking.models.Booking.validate_time]),
        ),
    ]
