# Generated by Django 5.0.2 on 2024-02-26 19:13

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(validators=[booking.models.Booking.validate_date]),
        ),
    ]
