# Generated by Django 5.0.2 on 2024-02-26 19:16

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.SmallIntegerField(default=1, validators=[booking.models.Booking.validate_guests]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(validators=[booking.models.Booking.validate_time]),
        ),
    ]
