# Generated by Django 5.0.2 on 2024-03-07 16:06

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_booking_guests_alter_booking_occasion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.SmallIntegerField(default=1, validators=[booking.models.Booking.validate_guests]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='occasion',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Birthday', 'Birthday'), ('Anniversary', 'Anniversary')], default='Casual', max_length=12),
        ),
    ]
