# Generated by Django 5.0.2 on 2024-02-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='featured',
        ),
    ]
